@startuml
title <size:24>Daily Brief</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("NewsBriefApplication_boundary", "NewsBriefApplication", $tags="") {
  Container_Boundary("NewsBriefApplication.NewsBriefApplication_boundary", "NewsBriefApplication", $tags="") {
    Component(NewsBriefApplication.NewsBriefApplication.NewsAcquisition, "News Acquisition", $techn="Module", $descr="", $tags="", $link="")
    Component(NewsBriefApplication.NewsBriefApplication.AISummarization, "AI Summarization", $techn="Module", $descr="", $tags="", $link="")
    Component(NewsBriefApplication.NewsBriefApplication.DailyBrief, "Daily Brief", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(NewsBriefApplication.NewsBriefApplication.DailyBrief, NewsBriefApplication.NewsBriefApplication.AISummarization, "uses", $techn="", $tags="", $link="")
Rel(NewsBriefApplication.NewsBriefApplication.DailyBrief, NewsBriefApplication.NewsBriefApplication.NewsAcquisition, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml