@startuml
title <size:24>AI Summarization</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("NewsBriefApplication_boundary", "NewsBriefApplication", $tags="") {
  Container_Boundary("NewsBriefApplication.NewsBriefApplication_boundary", "NewsBriefApplication", $tags="") {
    Component(NewsBriefApplication.NewsBriefApplication.SharedKernel, "Shared Kernel", $techn="Module", $descr="", $tags="", $link="")
    Component(NewsBriefApplication.NewsBriefApplication.AISummarization, "AI Summarization", $techn="Module", $descr="", $tags="", $link="")
  }

}

Rel(NewsBriefApplication.NewsBriefApplication.AISummarization, NewsBriefApplication.NewsBriefApplication.SharedKernel, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
hide stereotypes
@enduml